 const data = [ 
    {
          id: 1,
          name: "Curve",
          category: "Chairs",
          img: "./10016.jpg",
          price: 320.0,
          rating: 5,
          colors: [],
        },
        {
          id: 2,
          name: "Can",
          category: "Sofas",
          img: "./10017.jpg",
          price: 2100.0,
          rating: null,
          colors: [],
        },
        {
          id: 3,
          name: "Giro LR",
          category: "Tables",
          img: "./10018.jpg",
          price: 680.0,
          rating: null,
          colors: [{name : "American Silver" , code : "rgb(205,206,208)"},
            {name : "French Bistre" , code : "rgb(127,111,75)"},
            {name : "Gray" ,code : "rgb(129,122,130)"}
          ]
        },
    {
      id: 4,
      name: "Belt",
      category: "Armchairs",
      img: "./10030.jpg",
      price: 449.0,
      rating: null,
      colors: [],
    },
    {
      id: 5,
      name: "Soft Edge",
      category: "Chairs",
      img: "./10019.jpg",
      price: 440.0,
      rating: null,
      colors: [{ name: "American Silver", code: "rgb(205,206,208)" },
            { name: "Jet", code: "rgb(54,54,54)" },
            { name: "Venetian Red", code: "rgb(204,21,18)" },
          ],
    },
    {
      id: 6,
      name: "Pallisade",
      category: "Sofas",
      img: "./10020.jpg",
      price: 1890.0,
      rating: null,
      colors: [],
    },
    {
      id: 7,
      name: "Bitta",
      category: "Tables",
      img: "./10021.jpg",
      price: 1519.0,
      rating: null,
      colors: [],
    },
    {
      id: 8,
      name: "Albert",
      category: "Armchairs",
      img: "./10081.jpg",
      price: 1600.0,
      rating: null,
      colors: [{name : "French Bistre" , code : "rgb(127,111,75)"},
        { name: "Jet", code: "rgb(54,54,54)" }
      ],
    },
    {
      id: 9,
      name: "Navona",
      category: "Sofas",
      img: "./10022.jpg",
      price: 1669.0,
      rating: null,
      colors: [],
    },
    {
      id: 10,
      name: "Aruda",
      category: "Tables",
      img: "./10023.jpg",
      price: 699.0,
      rating: null,
      colors: [],
    },
  ];
  module.exports = data;