const data = [
{
    id: 5,
    name: "Henry",
    category: "Tables",
    img: "/wd-furniture-tables-prod-4-1.jpg",
    price: 2090.0,
    rating: 4.5,
    colors: [],
  },
{
    id: 34,
    name: "Delaunait Quilt",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-4-1.jpg",
    price: 1259.0,
    rating: 5,
    colors: [],
  },
{
    id: 110,
    name: "Mayday Outdoor",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-3-1.jpg",
    price: 140,
    rating: null,
    colors: []
  },
{
    id: 93,
    name: "Hem",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-4-1.jpg",
    price: 45,
    rating: null,
    colors: []
  },
{
    id: 158,
    name: "Srandford Bridge",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-4-1-400x457.jpg",
    price: 720.0,
    rating: null,
    colors: []
  },
{
    id: 39,
    name: "Elephant",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-12-1.jpg",
    price: 1820.0,
    rating: 0,
    colors: [],
  },
{
        id: 128,
        name: "Chicken Racing Car",
        category: "Toys",
        img: "/wd-furniture-toys-prod-1-1.jpg",
        price: 25,
        rating: null,
        colors: []
    },
{
    id: 149,
    name: "Curve",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-1-1-400x457.jpg",
    price: 320.0,
    rating: 4.5,
    colors: []
  },
{
    id: 18,
    name: "Angel",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-13-1.jpg",
    price: 2100.0,
    rating: 5,
    colors: [],
  },
{
        id: 126,
        name: "Palomino",
        category: "Toys",
        img: "/wd-furniture-toys-prod-3-1.jpg",
        price: 93,
        rating: null,
        colors: []
    },
{
        id: 63,
        name: "Gentelman Night",
        category: "Beds",
        img: "/wd-furniture-beds-prod-2-1.jpg",
        price: 2300,
        rating: null,
        colors: []
    },
{
    id: 37,
    name: "Julep",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-14-1.jpg",
    price: 620.0,
    rating: 0,
    colors: [],
  },
{
    id: 101,
    name: "Mademoiselle",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-12-1.jpg",
    price: 1100,
    rating: null,
    colors: []
  },
{
        id: 119,
        name: "Panda Bear",
        category: "Toys",
        img: "/wd-furniture-toys-prod-10-1.jpg",
        price: 16,
        rating: null,
        colors: []
    },
{
        id: 117,
        name: "Lullaby Bunny",
        category: "Toys",
        img: "/wd-furniture-toys-prod-12-1.jpg",
        price: 60,
        rating: null,
        colors: []
    },
{
    id: 71,
    name: "Trust",
    category: "Storage",
    img: "/wd-furniture-storage-prod-11-1.jpg",
    price: 3200,
    rating: null,
    colors: []
  },
{
    id: 136,
    name: "Tarracota Vase",
    category: "Decor",
    img: "/wd-furniture-decor-prod-9-1.jpg",
    price: 240,
    rating: null,
    colors: []
  },
{
    id: 147,
    name: "Sophie",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-5-1-400x457.jpg",
    price: 520.0,
    rating: 5.0,
    colors: []
  },
{
    id: 36,
    name: "Lima",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-15-1.jpg",
    price: 460.0,
    rating: 0,
    colors: [],
  },
{
    id: 74,
    name: "Ottavia",
    category: "Storage",
    img: "/wd-furniture-storage-prod-7-1.jpg",
    price: 1320,
    rating: null,
    colors: []
  },
{
    id: 21,
    name: "Polder",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-2-1.jpg",
    price: 1876.0,
    rating: 4.5,
    colors: [],
  },
{
    id: 44,
    name: "Mira",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-7-1.jpg",
    price: 450.0,
    rating: 0,
    colors: [],
  },
{
        id: 120,
        name: "Silicone Nesting Toy",
        category: "Toys",
        img: "/wd-furniture-toys-prod-9-1.jpg",
        price: 19,
        rating: null,
        colors: []
    },
{
    id: 133,
    name: "Edelstahl Besteck",
    category: "Decor",
    img: "/wd-furniture-decor-prod-12-1.jpg",
    price: 25,
    rating: null,
    colors: []
  },
{
    id: 157,
    name: "Ventura",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-6-1-400x457.jpg",
    price: 488.0,
    rating: null,
    colors: []
  },
{
        id: 115,
        name: "Safari Elephant",
        category: "Toys",
        img: "/wd-furniture-toys-prod-14-1.jpg",
        price: 40,
        rating: null,
        colors: []
    },
{
    id: 81,
    name: "Stonewashed Tana",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-16-1.jpg",
    price: 67,
    rating: null,
    colors: []
  },
{
    id: 16,
    name: "Oakly",
    category: "Tables",
    img: "/wd-furniture-tables-prod-12-1.jpg",
    price: 1100.0,
    rating: 5.0,
    colors: [] },
{
    id: 148,
    name: "Petit",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-12-1-400x457.jpg",
    price: 327.0,
    rating: 4.5,
    colors: []
  },
{
    id: 23,
    name: "Fellini",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-14-1.jpg",
    price: 2760.0,
    rating: 0,
    colors: [],
  },
{
    id: 92,
    name: "Max",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-5-1.jpg",
    price: 1180,
    rating: null,
    colors: []
  },
{
        id: 125,
        name: "Fraction Blocks",
        category: "Toys",
        img: "/wd-furniture-toys-prod-4-1.jpg",
        price: 22.3,
        rating: null,
        colors: []
    },
{
    id: 27,
    name: "Mags",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-9-1.jpg",
    price: 3620.0,
    rating: 0,
    colors: [],
  },
{
    id: 15,
    name: "Apollo",
    category: "Tables",
    img: "/wd-furniture-tables-prod-11-1.jpg",
    price: 2200.0,
    rating: 5.0,
    colors: [],
  },
{
    id: 137,
    name: "Kastle",
    category: "Decor",
    img: "/wd-furniture-decor-prod-8-1.jpg",
    price: 290,
    rating: null,
    colors: []
  },
{
    id: 42,
    name: "Mercury",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-9-1.jpg",
    price: 1300.0,
    rating: 0,
    colors: [],
  },
{
    id: 22,
    name: "Savile Row",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-15-1.jpg",
    price: 1949.0,
    rating: 0,
    colors: [],
  },
{
    id: 109,
    name: "Skygarden",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-4-1.jpg",
    price: 780,
    rating: null,
    colors: []
  },
{
    id: 13,
    name: "Albus",
    category: "Tables",
    img: "/wd-furniture-tables-prod-3-1.jpg",
    price: 799.0,
    rating: 5.0,
    colors: [],
  },
{
    id: 111,
    name: "Bellop",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-2-1.jpg",
    price: 200,
    rating: null,
    colors: []
  },
{
        id: 60,
        name: "Ricordi",
        category: "Beds",
        img: "/wd-furniture-beds-prod-6-1.jpg",
        price: 2450,
        rating: null,
        colors: []
    },
{
    id: 105,
    name: "Sawaru",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-8-1.jpg",
    price: 630,
    rating: null,
    colors: []
  },
{
    id: 67,
    name: "Niky",
    category: "Storage",
    img: "/wd-furniture-storage-prod-14-1.jpg",
    price: 640,
    rating: null,
    colors: []
  },
{
    id: 160,
    name: "Ipanema",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-2-1-400x457.jpg",
    price: 540.0,
    rating: null,
    colors: []
  },
{
    id: 47,
    name: "Daiki Studio",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-3-1.jpg",
    price: 1200.0,
    rating: 0,
    colors: [],
  },
{
    id: 104,
    name: "Bela",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-9-1.jpg",
    price: 240,
    rating: null,
    colors: []
  },
{
    id: 100,
    name: "Horse on Courbette",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-13-1.jpg",
    price: 945,
    rating: null,
    colors: []
  },
{
        id: 59,
        name: "Grangala",
        category: "Beds",
        img: "/wd-furniture-beds-prod-7-1.jpg",
        price: 2840,
        rating: null,
        colors: []
    },
{
    id: 8,
    name: "Motta",
    category: "Tables",
    img: "/wd-furniture-tables-prod-5-1.jpg",
    price: 1.0,
    rating: 4.0,
    colors: [],
  },
{
    id: 129,
    name: "Tesse",
    category: "Decor",
    img: "/wd-furniture-decor-prod-16-1.jpg",
    price: 22,
    rating: null,
    colors: []
  },
{
    id: 85,
    name: "Miha",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-12-1.jpg",
    price: 120,
    rating: null,
    colors: []
  },
{
    id: 3,
    name: "Aruda",
    category: "Tables",
    img: "/wd-furniture-tables-prod-16-1.jpg",
    price: 699.0,
    rating: 4.5,
    colors: [],
  },
{
    id: 7,
    name: "Ringer",
    category: "Tables",
    img: "/wd-furniture-tables-prod-14-1.jpg",
    price: 0.0,
    rating: 0,
    colors: [],
  },
{
    id: 89,
    name: "Louise",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-8-1.jpg",
    price: 230,
    rating: null,
    colors: []
  },
{
    id: 30,
    name: "Arbour",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-4-1.jpg",
    price: 1900.0,
    rating: 0,
    colors: [],
  },
{
    id: 1,
    name: "Giro LR",
    category: "Tables",
    img: "/wd-furniture-tables-prod-13-1.jpg",
    price: 449.0,
    rating: 5.0,
    colors: [],
  },
{
    id: 9,
    name: "Sylva",
    category: "Tables",
    img: "/wd-furniture-tables-prod-6-1.jpg",
    price: 1390.0,
    rating: 4.0,
    colors: [],
  },
{
    id: 20,
    name: "Palissade",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-7-1.jpg",
    price: 1890.0,
    rating: 4.5,
    colors: [],
  },
{
        id: 64,
        name: "Park 1",
        category: "Beds",
        img: "/wd-furniture-beds-prod-1-1.jpg",
        price: 2680,
        rating: null,
        colors: []
    },
{
        id: 51,
        name: "Brera",
        category: "Beds",
        img: "/wd-furniture-beds-prod-15-1.jpg",
        price: 1520,
        rating: null,
        colors: []
    },
{
    id: 45,
    name: "Reeves Large",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-6-1.jpg",
    price: 825.0,
    rating: 0,
    colors: [],
  },
{
    id: 78,
    name: "Comb. 101",
    category: "Storage",
    img: "/wd-furniture-storage-prod-3-1.jpg",
    price: 208,
    rating: null,
    colors: []
  },
{
    id: 32,
    name: "Freeform",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-1-1.jpg",
    price: 2800.0,
    rating: 0,
    colors: [],
  },
{
    id: 25,
    name: "Netha",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-11-1.jpg",
    price: 2340.0,
    rating: 0,
    colors: [],
  },
{
    id: 73,
    name: "Piedra",
    category: "Storage",
    img: "/wd-furniture-storage-prod-8-1.jpg",
    price: 895,
    rating: null,
    colors: []
  },
{
    id: 68,
    name: "Moore",
    category: "Storage",
    img: "/wd-furniture-storage-prod-13-1.jpg",
    price: 45,
    rating: null,
    colors: []
  },
{
    id: 107,
    name: "Aim",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-6-1.jpg",
    price: 320,
    rating: null,
    colors: []
  },
{
    id: 91,
    name: "Isabel",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-6-1.jpg",
    price: 15,
    rating: null,
    colors: []
  },
{
    id: 130,
    name: "Oree",
    category: "Decor",
    img: "/wd-furniture-decor-prod-15-1.jpg",
    price: 289,
    rating: null,
    colors: []
  },
{
    id: 80,
    name: "Colour Cabinet",
    category: "Storage",
    img: "/wd-furniture-storage-prod-1-1.jpg",
    price: 669,
    rating: null,
    colors: []
  },
{
    id: 35,
    name: "Sendai",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-1-1.jpg",
    price: 679.0,
    rating: 5,
    colors: [],
  },
{
    id: 38,
    name: "Kelly",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-13-1.jpg",
    price: 740.0,
    rating: 0,
    colors: [],
  },
{
    id: 83,
    name: "Architecture Throw",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-14-1.jpg",
    price: 380,
    rating: null,
    colors: []
  },
{
    id: 33,
    name: "Reversivel",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-16-1.jpg",
    price: 855.0,
    rating: 5,
    colors: [],
  },
{
    id: 144,
    name: "Cushion",
    category: "Decor",
    img: "/wd-furniture-decor-prod-1-1.jpg",
    price: 45,
    rating: null,
    colors: []
  },
{
    id: 70,
    name: "Newest",
    category: "Storage",
    img: "/wd-furniture-storage-prod-9-1.jpg",
    price: 640,
    rating: null,
    colors: []
  },
{
    id: 86,
    name: "Zaid",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-11-1.jpg",
    price: 780,
    rating: null,
    colors: []
  },
{
    id: 14,
    name: "Edge",
    category: "Tables",
    img: "/wd-furniture-tables-prod-8-1.jpg",
    price: 1369.0,
    rating: 5.0,
    colors: [],
  },
{
    id: 139,
    name: "Marble circles",
    category: "Decor",
    img: "/wd-furniture-decor-prod-6-1.jpg",
    price: 120,
    rating: null,
    colors: []
  },
{
    id: 150,
    name: "16 side",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-16-1-400x457.jpg",
    price: 295.0,
    rating: null,
    colors: []
  },
{
    id: 40,
    name: "Ca’foscari",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-11-1.jpg",
    price: 1326.0,
    rating: 0,
    colors: [],
  },
{
    id: 112,
    name: "Skynest",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-1-1.jpg",
    price: 620,
    rating: null,
    colors: []
  },
{
        id: 127,
        name: "Rabbit Racing Car",
        category: "Toys",
        img: "/wd-furniture-toys-prod-2-1.jpg",
        price: 25,
        rating: null,
        colors: []
    },
{
    id: 48,
    name: "Belt",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-2-1.jpg",
    price: 680.0,
    rating: 0,
    colors: [],
  },
{
    id: 28,
    name: "Silhouette",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-8-1.jpg",
    price: 1680.0,
    rating: 0,
    colors: [],
  },
{
    id: 65,
    name: "Materica",
    category: "Storage",
    img: "/wd-furniture-storage-prod-16-1.jpg",
    price: 3200,
    rating: null,
    colors: []
  },
{
    id: 6,
    name: "Brypo",
    category: "Tables",
    img: "/wd-furniture-tables-prod-15-1.jpg",
    price: 1579.0,
    rating: 0,
    colors: [],
  },
{
        id: 114,
        name: "Dancing Alligator",
        category: "Toys",
        img: "/wd-furniture-toys-prod-15-1.jpg",
        price: 32,
        rating: null,
        colors: []
    },
{
    id: 103,
    name: "Floor lamp",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-10-1.jpg",
    price: 320,
    rating: null,
    colors: []
  },
  {
    id: 81,
    name: "Stonewashed Tana",
    category: Textile,
    img: "./wd-furniture-textiles-prod-16-1.jpg",
    price: 67,
    rating: null,
    colors: []
  },
  {
    id: 82,
    name: "Maya Dune Linel",
    category: Textile,
    img: "./wd-furniture-textiles-prod-15-1.jpg",
    price: 530,
    rating: null,
    colors: []
  },
  {
    id: 83,
    name: "Architecture Throw",
    category: Textile,
    img: "./wd-furniture-textiles-prod-14-1.jpg",
    price: 380,
    rating: null,
    colors: []
  },
  {
    id: 84,
    name: "Green Sway",
    category: Textile,
    img: "./wd-furniture-textiles-prod-13-1.jpg",
    price: 2340,
    rating: null,
    colors: []
  },
  {
    id: 85,
    name: "Miha",
    category: Textile,
    img: "./wd-furniture-textiles-prod-12-1.jpg",
    price: 120,
    rating: null,
    colors: []
  },
  {
    id: 86,
    name: "Zaid",
    category: Textile,
    img: "./wd-furniture-textiles-prod-11-1.jpg",
    price: 780,
    rating: null,
    colors: []
  },
  {
    id: 87,
    name: "Nidodape",
    category: Textile,
    img: "./wd-furniture-textiles-prod-10-1.jpg",
    price: 16,
    rating: null,
    colors: []
  },
  {
    id: 88,
    name: "Cobblestone",
    category: Textile,
    img: "./wd-furniture-textiles-prod-9-1.jpg",
    price: 499,
    rating: null,
    colors: []
  },
  {
    id: 89,
    name: "Louise",
    category: Textile,
    img: "./wd-furniture-textiles-prod-8-1.jpg",
    price: 230,
    rating: null,
    colors: []
  },
  {
    id: 90,
    name: "Stoense",
    category: Textile,
    img: "./wd-furniture-textiles-prod-7-1.jpg",
    price: 230,
    rating: null,
    colors: []
  },
  {
    id: 91,
    name: "Isabel",
    category: Textile,
    img: "./wd-furniture-textiles-prod-6-1.jpg",
    price: 15,
    rating: null,
    colors: []
  },
  {
    id: 92,
    name: "Max",
    category: Textile,
    img: "./wd-furniture-textiles-prod-5-1.jpg",
    price: 1180,
    rating: null,
    colors: []
  },
  {
    id: 93,
    name: "Hem",
    category: Textile,
    img: "./wd-furniture-textiles-prod-4-1.jpg",
    price: 45,
    rating: null,
    colors: []
  },
  {
    id: 94,
    name: "Mediteranni",
    category: Textile,
    img: "./wd-furniture-textiles-prod-3-1.jpg",
    price: 540,
    rating: null,
    colors: []
  },
  {
    id: 95,
    name: "Mega Dot",
    category: Textile,
    img: "./wd-furniture-textiles-prod-2-1.jpg",
    price: 85,
    rating: null,
    colors: []
  },
  {
    id: 96,
    name: "Sentiero Di Fillipo",
    category: Textile,
    img: "./wd-furniture-textiles-prod-1-1.jpg",
    price: 3200,
    rating: null,
    colors: []
  }

  ,{
    id: 97,
    name: "Ivy&Seed",
    category: "Lighting",
    img: "./wd-furniture-lighting-prod-16-1.jpg",
    price: 130,
    rating: null,
    colors: []
  },
  {
    id: 98,
    name: "Mademoiselle Annette",
    category: "Lighting",
    img: "./wd-furniture-lighting-prod-15-1.jpg",
    price: 680,
    rating: null,
    colors: []
  },
{
    id: 10,
    name: "Raymond",
    category: "Tables",
    img: "/wd-furniture-tables-prod-10-1.jpg",
    price: 1229.0,
    rating: 4.0,
    colors: [],
  },
{
        id: 62,
        name: "Dream",
        category: "Beds",
        img: "/wd-furniture-beds-prod-4-1.jpg",
        price: 3100,
        rating: null,
        colors: []
    },
{
    id: 24,
    name: "Navona",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-12-1.jpg",
    price: 1669.0,
    rating: 0,
    colors: [],
  },
{
        id: 49,
        name: "Curve",
        category: "Beds",
        img: "/wd-furniture-beds-prod-3-1.jpg",
        price: 2800,
        rating: null,
        colors: []
    },
{
        id: 124,
        name: "Pasta",
        category: "Toys",
        img: "/wd-furniture-toys-prod-5-1.jpg",
        price: 24,
        rating: null,
        colors: []
    },
{
    id: 72,
    name: "Navona",
    category: "Storage",
    img: "/wd-furniture-storage-prod-10-1.jpg",
    price: 720,
    rating: null,
    colors: []
  },
{
    id: 66,
    name: "Herman",
    category: "Storage",
    img: "/wd-furniture-storage-prod-15-1.jpg",
    price: 825,
    rating: null,
    colors: []
  },
{
        id: 118,
        name: "Lullaby Elephant",
        category: "Toys",
        img: "/wd-furniture-toys-prod-11-1.jpg",
        price: 62,
        rating: null,
        colors: []
    },
{
    id: 75,
    name: "Astoria",
    category: "Storage",
    img: "/wd-furniture-storage-prod-6-1.jpg",
    price: 830,
    rating: null,
    colors: []
  },
{
    id: 84,
    name: "Green Sway",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-13-1.jpg",
    price: 2340,
    rating: null,
    colors: []
  },
{
    id: 138,
    name: "Faced Skull",
    category: "Decor",
    img: "/wd-furniture-decor-prod-7-1.jpg",
    price: 320,
    rating: null,
    colors: []
  },
{
    id: 17,
    name: "Twible",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-16-1.jpg",
    price: 2800.0,
    rating: 5,
    colors: [],
  },
{
    id: 98,
    name: "Mademoiselle Annette",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-15-1.jpg",
    price: 680,
    rating: null,
    colors: []
  },
{
    id: 132,
    name: "Versante",
    category: "Decor",
    img: "/wd-furniture-decor-prod-13-1.jpg",
    price: 210,
    rating: null,
    colors: []
  },
{
    id: 96,
    name: "Sentiero Di Fillipo",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-1-1.jpg",
    price: 3200,
    rating: null,
    colors: []
  },
{
    id: 11,
    name: "Novo",
    category: "Tables",
    img: "/wd-furniture-tables-prod-1-1.jpg",
    price: 1090.0,
    rating: 4.0,
    colors: [],
  },
{
    id: 95,
    name: "Mega Dot",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-2-1.jpg",
    price: 85,
    rating: null,
    colors: []
  },
{
    id: 135,
    name: "Naturofantastic",
    category: "Decor",
    img: "/wd-furniture-decor-prod-10-1.jpg",
    price: 890,
    rating: null,
    colors: []
  },
{
    id: 143,
    name: "Meteo S",
    category: "Decor",
    img: "/wd-furniture-decor-prod-2-1.jpg",
    price: 220,
    rating: null,
    colors: []
  },
{
    id: 140,
    name: "Whale",
    category: "Decor",
    img: "/wd-furniture-decor-prod-5-1.jpg",
    price: 43,
    rating: null,
    colors: []
  },
{
        id: 50,
        name: "Keen",
        category: "Beds",
        img: "/wd-furniture-beds-prod-16-1.jpg",
        price: 2100,
        rating: null,
        colors: []
    },
{
    id: 12,
    name: "Nero",
    category: "Tables",
    img: "/wd-furniture-tables-prod-9-1.jpg",
    price: 1560.0,
    rating: 4.0,
    colors: [],
  },
{
    id: 154,
    name: "Frames Upholstered",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-10-1-400x457.jpg",
    price: 399.0,
    rating: null,
    colors: []
  },
{
        id: 56,
        name: "Azul",
        category: "Beds",
        img: "/wd-furniture-beds-prod-10-1.jpg",
        price: 828,
        rating: null,
        colors: []
    },
{
    id: 2,
    name: "Kensington",
    category: "Tables",
    img: "/wd-furniture-tables-prod-2-1.jpg",
    price: 290.0,
    rating: 5.0,
    colors: [],
  },
{
    id: 94,
    name: "Mediteranni",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-3-1.jpg",
    price: 540,
    rating: null,
    colors: []
  },
{
    id: 87,
    name: "Nidodape",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-10-1.jpg",
    price: 16,
    rating: null,
    colors: []
  },
{
    id: 4,
    name: "Eames Segmented",
    category: "Tables",
    img: "/wd-furniture-tables-prod-7-1.jpg",
    price: 3200.0,
    rating: 4.5,
    colors: [],
  },
{
    id: 90,
    name: "Stoense",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-7-1.jpg",
    price: 230,
    rating: null,
    colors: []
  },
{
        id: 57,
        name: "Tepu",
        category: "Beds",
        img: "/wd-furniture-beds-prod-9-1.jpg",
        price: 1300,
        rating: null,
        colors: []
    },
{
    id: 82,
    name: "Maya Dune Linel",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-15-1.jpg",
    price: 530,
    rating: null,
    colors: []
  },
{
    id: 155,
    name: "Hal Wood",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-8-1-400x457.jpg",
    price: 625.0,
    rating: null,
    colors: []
  },
{
        id: 55,
        name: "Edoardo Kuoio",
        category: "Beds",
        img: "/wd-furniture-beds-prod-11-1.jpg",
        price: 1100,
        rating: null,
        colors: []
    },
{
        id: 121,
        name: "Baby Key Rattle",
        category: "Toys",
        img: "/wd-furniture-toys-prod-8-1.jpg",
        price: 120,
        rating: null,
        colors: []
    },
{
    id: 106,
    name: "Foglio",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-7-1.jpg",
    price: 445,
    rating: null,
    colors: []
  },
{
    id: 108,
    name: "Flauta Riga",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-5-1.jpg",
    price: 399,
    rating: null,
    colors: []
  },
{
    id: 141,
    name: "Bird",
    category: "Decor",
    img: "/wd-furniture-decor-prod-4-1.jpg",
    price: 75,
    rating: null,
    colors: []
  },
{
    id: 41,
    name: "Rosemary",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-10-1.jpg",
    price: 899.0,
    rating: 0,
    colors: [],
  },
{
    id: 31,
    name: "Mariposa",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-3-1.jpg",
    price: 1720.0,
    rating: 0,
    colors: [],
  },
{
    id: 69,
    name: "Crossing",
    category: "Storage",
    img: "/wd-furniture-storage-prod-12-1.jpg",
    price: 200,
    rating: null,
    colors: []
  },
{
    id: 79,
    name: "Colour Cabinet S",
    category: "Storage",
    img: "/wd-furniture-storage-prod-2-1.jpg",
    price: 450,
    rating: null,
    colors: []
  },
{
    id: 77,
    name: "Comb. 401",
    category: "Storage",
    img: "/wd-furniture-storage-prod-4-1.jpg",
    price: 110,
    rating: null,
    colors: []
  },
{
    id: 26,
    name: "Can",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-10-1.jpg",
    price: 2100.0,
    rating: 0,
    colors: [],
  },
{
    id: 134,
    name: "Peonies",
    category: "Decor",
    img: "/wd-furniture-decor-prod-11-1.jpg",
    price: 990,
    rating: null,
    colors: []
  },
{
    id: 46,
    name: "Albert",
    category: "Armchairs",
    img: "/wd-furniture-armchairs-prod-5-1.jpg",
    price: 1600.0,
    rating: 0,
    colors: [],
  },
{
    id: 19,
    name: "Quilton",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-6-1.jpg",
    price: 2100.0,
    rating: 5,
    colors: [],
  },
{
    id: 102,
    name: "Mia",
    category: "Lighting",
    img: "/wd-furniture-lighting-prod-11-1.jpg",
    price: 635,
    rating: null,
    colors: []
  },
{
    id: 152,
    name: "Soft Edge",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-13-1-400x457.jpg",
    price: 440.0,
    rating: null,
    colors: []
  },
{
    id: 88,
    name: "Cobblestone",
    category: "Textile",
    img: "/wd-furniture-textiles-prod-9-1.jpg",
    price: 499,
    rating: null,
    colors: []
  },
{
    id: 156,
    name: "Fauteuil Direction",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-7-1-400x457.jpg",
    price: 372.0,
    rating: null,
    colors: []
  },
{
    id: 151,
    name: "12 side",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-14-1-400x457.jpg",
    price: 375.0,
    rating: null,
    colors: []
  },
{
    id: 142,
    name: "Measuring Cup",
    category: "Decor",
    img: "/wd-furniture-decor-prod-3-1.jpg",
    price: 12,
    rating: null,
    colors: []
  },
{
    id: 145,
    name: "Revolt",
    category: "Chairs",
    img: "https://woodmart.xtemos.com/furniture2/wp-content/uploads/sites/11/2023/04/wd-furniture-chair-prod-15-1-400x457.jpg",
    price: 275.0,
    rating: 5.0,
    colors: []
  },
{
    id: 29,
    name: "Mikonsa",
    category: "Sofas",
    img: "/wd-furniture-sofas-prod-5-1.jpg",
    price: 1349.0,
    rating: 0,
    colors: [],
  }
];

module.exports = data;
